### PR TITLE
Improve development instructions in Readme file

### PR DESCRIPTION
**Pull request by vlad-tim**
# Contribution checklist

## Brief description

This change improves troubleshooting instructions for developers who encounter build issues.

For context, when I did `git bisect` and ran into numerous unexpected build issues when switching from one git revision to another and then attempting to build the project, error example:

```
error TS7016: Could not find a declaration file for module '@hcengineering/server-request'
```

In order to resolve them I tried multiple action including:

* Using troubleshooting tips from the existing Readme, in particular `rush build --clean`.
* Complete deletion of docker files (containers, images, volumes, etc) by removing contents of `/var/lib/docker/` directory.
* Cloning a fresh version of the repository from git.
* Rebooting the machine.
* Using `rush rebuild` and `rush purge`.
* **Manually deleting the build cache**.

The last action turned out to be the only action that reliably overcame unexpected build issues for me.

Moreover, I believe that the existing advice to run `rush build --clean` is misleading because the cache is *still used* according to the output of this command:

```
[user@huly] ➜  ~/workshops/platform git:(improve-dev-readme) ✗ rush build --clean                                                                                                                                              

Rush Multi-Project Build Tool 5.115.0 - https://rushjs.io
Node.js version is 20.11.1 (LTS)

Starting "rush build"

Analyzing repo state... DONE (0.07 seconds)

Executing a maximum of 2 simultaneous processes...

==[ @hcengineering/platform-rig (build) ]========================[ 1 of 225 ]==
"@hcengineering/platform-rig (build)" did not define any work.

==[ @hcengineering/platform (build) ]============================[ 2 of 225 ]==
"@hcengineering/platform (build)" was restored from the build cache.

==[ @hcengineering/apm (build) ]=================================[ 3 of 225 ]==
"@hcengineering/apm (build)" was restored from the build cache.
...
```

This Readme update is useful for new developers because it may save them a lot of time if they run into the same problems like I did.

## Checklist

(all boxes are checked as N/A for a documentation change)

* [x] - UI test added to added/changed functionality?
* [x] - Screenshot is added to PR if applicable ?
* [x] - Does a local formatting is applied (rush format)
* [x] - Does a local svelte-check is applied (rush svelte-check)
* [x] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [x] - Does the code work? Check whether function and logic are correct.
* [x] - Does Changelog.md is updated with changes?
* [x] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [x] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [x] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [x] - Does new code is well documented ?

## Related issues

https://github.com/hcengineering/platform/pull/4757

## Contributor requirements

* [x] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [x] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

**Comment by haiodo** [comment]
Hi @vlad-timofeev, really sorry for this inconveniences, thanks for PR in any case. I've just missed to update readme, since we switched to build using `esbuild` mostly and move typescript validation into `rush validate` phase.
So will update readme ASAP.
Thanks.

**Review by haiodo — APPROVED** [review]

**Comment by vlad-tim** [comment]
Thanks for the information and no worries - I did not mean to complain.
